import { useSearchParams } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { Check, ArrowUpRight, ShieldCheck, Sparkles, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '../lib/api';
import { useWorkspace, useWorkspaceQuery, useRefreshWorkspace, useWorkspacePath, useSession } from '../lib/session';
import type { Billing } from '../lib/types';
import { dateTime } from '../lib/format';
import { Button, PageHeading, Loading, ErrorState } from '../components/ui';
export function BillingPage() {
  const query = useWorkspaceQuery<Billing>('billing', '/billing', '', true); const { workspace } = useWorkspace(); const { session } = useSession(); const path = useWorkspacePath(); const refresh = useRefreshWorkspace(); const [search] = useSearchParams();
  const action = useMutation({ mutationFn: (kind: 'checkout' | 'portal') => api<{ url: string }>(path(`/billing/${kind}`), { method: 'POST' }), onSuccess: data => { window.location.assign(data.url); }, onError: (error: Error) => toast.error(error.message) });
  if (query.isPending) return <Loading />; if (query.error) return <ErrorState error={query.error} retry={query.refetch} />;
  const data = query.data; const canManage = workspace.role === 'OWNER' && Boolean(session?.user.emailVerified); const labels = { projects: 'Projetos ativos', members: 'Integrantes e convites', tasks: 'Tarefas armazenadas' };
  return <><PageHeading eyebrow="ESPAÇO PARA CRESCER" title="Seu plano" description="A assinatura pertence à equipe. Cada workspace tem seu próprio plano."><Button variant="secondary" onClick={() => refresh()}><RefreshCw size={16} />Atualizar status</Button></PageHeading>
    {search.get('checkout') === 'success' && <div className="info-banner">Checkout finalizado. O plano só muda após a confirmação da assinatura pelo servidor. Esta tela consulta o status automaticamente.</div>}
    {!data.configured && <div className="info-banner">A cobrança não está configurada neste ambiente. O plano Free funciona sem Stripe; nenhum pagamento será simulado.</div>}
    <section className="panel current-plan"><div className="current-plan-title"><div className="plan-symbol"><Sparkles size={24} /></div><div><span className="eyebrow">SEU PLANO ATUAL</span><h2>{data.plan === 'PRO' ? 'Nexo Pro' : 'Nexo Free'}</h2><p>{data.syncedAt ? `Última sincronização: ${dateTime(data.syncedAt)}` : 'Comece a organizar seu trabalho sem cartão.'}</p></div>{data.hasCustomer && <Button variant="secondary" busy={action.isPending} disabled={!canManage || !data.configured} onClick={() => action.mutate('portal')}>Gerenciar assinatura <ArrowUpRight size={16} /></Button>}</div><div className="usage-grid">{(['projects', 'members', 'tasks'] as const).map(key => <div key={key}><div><span>{labels[key]}</span><strong>{data.usage[key]} <small>/ {data.limits[key]}</small></strong></div><progress value={Math.min(data.usage[key], data.limits[key])} max={data.limits[key]} aria-label={labels[key]} />{data.usage[key] > data.limits[key] && <small className="danger-text">Acima do limite. Seus dados foram preservados.</small>}</div>)}</div></section>
    <div className="pricing-grid">{(['FREE', 'PRO'] as const).map(plan => <article className={`pricing-card ${plan === 'PRO' ? 'highlighted' : ''}`} key={plan}><div className="pricing-top"><span>{data.plans[plan].name}</span>{plan === 'PRO' && <span className="badge">PARA EQUIPES EM CRESCIMENTO</span>}</div><h2>{plan === 'FREE' ? 'O essencial para começar.' : 'Mais espaço para construir.'}</h2><strong className="pricing-value">{plan === 'FREE' ? 'Grátis' : 'Valor no checkout'}</strong><p>{plan === 'FREE' ? 'Organização para seus primeiros projetos.' : 'O valor e a periodicidade são definidos no produto configurado na Stripe.'}</p><div className="plan-features">{[`${data.plans[plan].projects} projetos ativos`, `${data.plans[plan].members} pessoas por equipe`, `${data.plans[plan].tasks.toLocaleString('pt-BR')} tarefas armazenadas`, 'Quadro, lista e histórico de atividades'].map(feature => <span key={feature}><Check size={17} />{feature}</span>)}</div>{plan === data.plan ? <Button variant="secondary" disabled>Seu plano atual</Button> : plan === 'PRO' ? <Button busy={action.isPending} disabled={!canManage || !data.configured} onClick={() => action.mutate('checkout')}>Conhecer o Pro <ArrowUpRight size={16} /></Button> : <Button variant="secondary" disabled={!canManage || !data.configured || !data.hasCustomer} busy={action.isPending} onClick={() => action.mutate('portal')}>Gerenciar cancelamento</Button>}</article>)}</div>
    <div className="billing-note"><ShieldCheck size={21} /><p>O Nexo não recebe os dados do seu cartão. Checkout, forma de pagamento e cancelamento ficam no portal da Stripe. Apenas o proprietário com e-mail confirmado pode gerenciar a assinatura.</p></div><p className="muted small-text">Regra deste exemplo: assinaturas active ou trialing com o preço configurado liberam o Pro. Outros estados aplicam limites Free, sem excluir dados existentes.</p>
  </>;
}
