import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, FolderKanban, CircleDashed, CircleCheck, Clock3, Plus } from 'lucide-react';
import { useSession, useWorkspace, useWorkspaceQuery } from '../lib/session';
import type { Dashboard } from '../lib/types';
import { dateOnly, dateTime } from '../lib/format';
import { Avatar, EmptyState, ErrorState, Loading, PageHeading, StatusBadge } from '../components/ui';
export function DashboardPage() {
  const query = useWorkspaceQuery<Dashboard>('dashboard', '/dashboard'); const { session } = useSession(); const { workspace } = useWorkspace();
  if (query.isPending) return <Loading />; if (query.error) return <ErrorState error={query.error} retry={query.refetch} />;
  const data = query.data; const total = data.counts.TODO + data.counts.IN_PROGRESS + data.counts.DONE; const done = total ? Math.round(data.counts.DONE / total * 100) : 0;
  const stats = [{ title: 'Projetos ativos', value: data.projects, icon: FolderKanban, note: 'Ideias em movimento', tone: 'purple' }, { title: 'Em andamento', value: data.counts.IN_PROGRESS, icon: CircleDashed, note: 'Tarefas sendo construídas', tone: 'blue' }, { title: 'Concluídas', value: data.counts.DONE, icon: CircleCheck, note: 'Etapas já entregues', tone: 'green' }, { title: 'Prazo vencido', value: data.overdue, icon: Clock3, note: 'Precisam da sua atenção', tone: 'orange' }];
  return <><PageHeading eyebrow="VISÃO GERAL" title={`Olá, ${session?.user.name.split(' ')[0]}.`} description="Seu trabalho, em movimento. Veja o que merece atenção hoje.">{workspace.role !== 'VIEWER' && <Link to="/app/tarefas?nova=1" className="button primary"><Plus size={17} />Nova tarefa</Link>}</PageHeading>
    <div className="stats-grid">{stats.map(stat => <article className="stat-card" key={stat.title}><div className="stat-top"><span>{stat.title}</span><span className={`stat-icon ${stat.tone}`}><stat.icon size={18} /></span></div><strong>{stat.value}</strong><small>{stat.note}</small></article>)}</div>
    <div className="dashboard-middle"><article className="focus-banner"><div><span className="eyebrow">UM PASSO DE CADA VEZ</span><h2>Clareza para o que vem a seguir.</h2><p>Transforme grandes objetivos em pequenas entregas. Sua equipe tem {data.members} pessoa{data.members !== 1 ? 's' : ''} conectada{data.members !== 1 ? 's' : ''} a esse espaço.</p><Link to="/app/projetos">Explorar projetos <ArrowUpRight size={17} /></Link></div><div className="focus-art" aria-hidden="true"><span /><span /><span /><i>✦</i></div></article><article className="panel progress-panel"><div className="panel-heading"><h2>Ritmo da equipe</h2><span className="muted">{total} tarefas</span></div><div className="progress-value"><strong>{done}<small>%</small></strong><span>do trabalho<br />concluído</span></div><div className="stacked-progress" aria-label={`${done}% das tarefas concluídas`}><span className="done" style={{ width: `${total ? data.counts.DONE / total * 100 : 0}%` }} /><span className="doing" style={{ width: `${total ? data.counts.IN_PROGRESS / total * 100 : 0}%` }} /></div><div className="progress-legend"><span><i className="dot gray" />A fazer <b>{data.counts.TODO}</b></span><span><i className="dot purple" />Em andamento <b>{data.counts.IN_PROGRESS}</b></span><span><i className="dot green" />Concluídas <b>{data.counts.DONE}</b></span></div></article></div>
    <div className="dashboard-bottom"><article className="panel"><div className="panel-heading"><div><h2>Próximas entregas</h2><p>Priorize o que está mais perto do prazo.</p></div><Link to="/app/tarefas" className="text-link">Ver todas <ArrowRight size={15} /></Link></div>{data.recentTasks.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Tarefa</th><th>Prazo</th><th>Status</th></tr></thead><tbody>{data.recentTasks.map(task => <tr key={task.id}><td><Link className="task-title" to={`/app/tarefas?projeto=${task.projectId}`}>{task.title}</Link><span className="table-subtitle">{task.project.name}</span></td><td className="nowrap">{dateOnly(task.dueDate)}</td><td><StatusBadge status={task.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="Espaço para novas ideias." description="Suas tarefas pendentes aparecerão aqui. Crie um projeto e comece." />}</article><article className="panel"><div className="panel-heading"><h2>Últimos movimentos</h2></div><div className="activity-feed">{data.activity.map(event => <div className="activity-item" key={event.id}><Avatar name={event.actor?.name || 'Sistema'} small /><div><strong>{event.summary}</strong><p>{event.actor?.name || 'Sistema'}</p><small>{dateTime(event.createdAt)}</small></div></div>)}{!data.activity.length && <p className="muted">As atividades da equipe aparecerão aqui.</p>}</div></article></div>
  </>;
}
