import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { Plus, Search, ArrowUpRight, Pencil, Archive, RotateCcw, Trash2, FolderKanban } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '../lib/api';
import { useWorkspace, useWorkspaceQuery, useRefreshWorkspace, useWorkspacePath } from '../lib/session';
import type { Project } from '../lib/types';
import { Button, Field, Modal, PageHeading, EmptyState, Loading, ErrorState } from '../components/ui';
export function ProjectsPage() {
  const query = useWorkspaceQuery<Project[]>('projects', '/projects'); const { workspace } = useWorkspace(); const path = useWorkspacePath(); const refresh = useRefreshWorkspace();
  const [status, setStatus] = useState<'ACTIVE' | 'ARCHIVED'>('ACTIVE'); const [search, setSearch] = useState('');
  const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Project | null>(null);
  const canManage = ['OWNER', 'ADMIN'].includes(workspace.role);
  const save = useMutation({ mutationFn: (body: unknown) => api(path(`/projects${editing ? `/${editing.id}` : ''}`), { method: editing ? 'PATCH' : 'POST', body }), onSuccess: async () => { await refresh(); setModal(false); toast.success(editing ? 'Projeto atualizado.' : 'Projeto criado.'); }, onError: (error: Error) => toast.error(error.message) });
  const action = useMutation({ mutationFn: ({ project, remove }: { project: Project; remove?: boolean }) => api(path(`/projects/${project.id}`), { method: remove ? 'DELETE' : 'PATCH', body: remove ? {} : { status: project.status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE' } }), onSuccess: async () => { await refresh(); toast.success('Projeto atualizado.'); }, onError: (error: Error) => toast.error(error.message) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); save.mutate(Object.fromEntries(new FormData(event.currentTarget))); }
  const projects = (query.data || []).filter(project => project.status === status && project.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  function open(project: Project | null) { setEditing(project); setModal(true); }
  return <><PageHeading eyebrow="DO PLANO À PRÁTICA" title="Projetos" description="Dê um lugar para cada ideia e acompanhe sua evolução.">{canManage && <Button onClick={() => open(null)}><Plus size={17} />Novo projeto</Button>}</PageHeading><div className="toolbar"><div className="segmented"><button className={status === 'ACTIVE' ? 'selected' : ''} onClick={() => setStatus('ACTIVE')}>Ativos</button><button className={status === 'ARCHIVED' ? 'selected' : ''} onClick={() => setStatus('ARCHIVED')}>Arquivados</button></div><label className="search-input"><Search size={17} /><input aria-label="Buscar projetos" placeholder="Buscar um projeto..." value={search} onChange={e => setSearch(e.target.value)} /></label></div>
    {query.isPending ? <Loading /> : query.error ? <ErrorState error={query.error} retry={query.refetch} /> : !projects.length ? <div className="panel"><EmptyState title="Nada por aqui ainda." description={search ? 'Tente buscar por outro nome.' : 'Comece com um projeto pequeno e transforme ideias em entregas.'}>{canManage && !search && <Button onClick={() => open(null)}><Plus size={16} />Criar projeto</Button>}</EmptyState></div> : <div className="projects-grid">{projects.map(project => { const progress = project.totalTasks ? Math.round(project.doneTasks / project.totalTasks * 100) : 0; return <article className="project-card" key={project.id}><div className="project-top"><div className={`project-icon color-${project.color}`}><FolderKanban size={23} /></div>{canManage && <div className="inline-actions"><button className="icon-button" title="Editar projeto" aria-label={`Editar projeto ${project.name}`} onClick={() => open(project)}><Pencil size={15} /></button><button className="icon-button" disabled={action.isPending} title={status === 'ACTIVE' ? 'Arquivar' : 'Reativar'} aria-label={`${status === 'ACTIVE' ? 'Arquivar' : 'Reativar'} ${project.name}`} onClick={() => action.mutate({ project })}>{status === 'ACTIVE' ? <Archive size={15} /> : <RotateCcw size={15} />}</button><button className="icon-button danger-text" disabled={action.isPending} title="Excluir projeto" aria-label={`Excluir projeto ${project.name}`} onClick={() => { if (window.confirm(`Excluir "${project.name}" e todas as suas tarefas? Esta ação não pode ser desfeita.`)) action.mutate({ project, remove: true }); }}><Trash2 size={15} /></button></div>}</div><h2>{project.name}</h2><p>{project.description || 'Um espaço para conectar suas próximas entregas.'}</p><div className="project-progress-label"><span>Progresso</span><strong>{progress}%</strong></div><progress value={progress} max={100} aria-label={`Progresso do projeto ${project.name}`} /><div className="project-footer"><span>{project.doneTasks}/{project.totalTasks} tarefas</span>{status === 'ACTIVE' ? <Link to={`/app/tarefas?projeto=${project.id}`}>Abrir projeto <ArrowUpRight size={16} /></Link> : <span className="badge">Arquivado</span>}</div></article>; })}</div>}
    <Modal open={modal} onOpenChange={value => { if (!save.isPending) setModal(value); }} title={editing ? 'Editar projeto' : 'Um novo começo'} description="Defina o contexto. As tarefas entram no próximo passo."><form key={editing?.id || 'new'} onSubmit={submit}><Field label="Nome do projeto *"><input name="name" required minLength={2} maxLength={100} defaultValue={editing?.name} placeholder="Ex.: Lançamento do site" /></Field><Field label="Descrição"><textarea name="description" rows={3} maxLength={2000} defaultValue={editing?.description} placeholder="Qual é o objetivo deste projeto?" /></Field><Field label="Cor de identificação"><select name="color" defaultValue={editing?.color || 'violet'}><option value="violet">Violeta</option><option value="blue">Azul</option><option value="emerald">Verde</option><option value="amber">Âmbar</option><option value="rose">Rosa</option></select></Field><div className="dialog-actions"><Button type="button" variant="secondary" disabled={save.isPending} onClick={() => setModal(false)}>Cancelar</Button><Button busy={save.isPending}>{editing ? 'Salvar alterações' : 'Criar projeto'}</Button></div></form></Modal>
  </>;
}
