import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { Save, LogOut, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { api, setCsrf } from '../lib/api';
import { useWorkspace, useSession, useWorkspaceQuery, useRefreshWorkspace, useWorkspacePath } from '../lib/session';
import type { Dashboard } from '../lib/types';
import { Avatar, Button, Field, PageHeading, Loading, ErrorState } from '../components/ui';
export function SettingsPage() {
  const { workspace } = useWorkspace(); const { session, refresh: refreshSession } = useSession(); const refresh = useRefreshWorkspace(); const path = useWorkspacePath(); const client = useQueryClient(); const navigate = useNavigate();
  const query = useWorkspaceQuery<Dashboard>('dashboard', '/dashboard'); const manage = ['OWNER', 'ADMIN'].includes(workspace.role);
  const save = useMutation({ mutationFn: (body: unknown) => api(path(''), { method: 'PATCH', body }), onSuccess: async () => { await refresh(); toast.success('Configurações salvas.'); }, onError: (error: Error) => toast.error(error.message) });
  const logoutAll = useMutation({ mutationFn: () => api('/auth/logout-all', { method: 'POST' }), onSuccess: async () => { setCsrf(''); client.removeQueries({ queryKey: ['workspace'] }); await refreshSession(); navigate('/entrar'); }, onError: (error: Error) => toast.error(error.message) });
  return <><PageHeading eyebrow="DO SEU JEITO" title="Configurações" description="Ajuste o contexto da equipe e cuide do acesso à sua conta." /><div className="settings-grid"><section className="panel settings-panel"><div className="panel-heading"><h2>Seu perfil</h2></div><div className="settings-content"><div className="profile-summary"><Avatar name={session?.user.name || ''} /><div><strong>{session?.user.name}</strong><p>{session?.user.email}</p><span className="badge">{session?.user.emailVerified ? 'E-mail confirmado' : 'E-mail pendente'}</span></div></div><p className="muted small-text">Seu perfil é compartilhado entre os workspaces dos quais você participa.</p><Link to="/esqueci-senha" className="text-link">Solicitar redefinição de senha ↗</Link></div></section><section className="panel settings-panel"><div className="panel-heading"><h2>Workspace</h2></div><div className="settings-content">{query.isPending ? <Loading /> : query.error ? <ErrorState error={query.error} retry={query.refetch} /> : <form key={workspace.id + workspace.name + query.data.timeZone} onSubmit={e => { e.preventDefault(); save.mutate(Object.fromEntries(new FormData(e.currentTarget))); }}><Field label="Nome da equipe"><input name="name" defaultValue={workspace.name} required minLength={2} maxLength={80} disabled={!manage} /></Field><Field label="Fuso horário" hint="Usado para identificar tarefas com prazo vencido."><select name="timeZone" defaultValue={query.data.timeZone} disabled={!manage}>{[...new Set([query.data.timeZone, 'America/Sao_Paulo', 'America/Bahia', 'America/Manaus', 'America/Recife', 'UTC'])].map(zone => <option key={zone} value={zone}>{zone}</option>)}</select></Field>{manage && <Button busy={save.isPending}><Save size={16} />Salvar alterações</Button>}</form>}</div></section></div><section className="panel section-gap settings-panel"><div className="panel-heading"><div><h2><ShieldCheck size={18} />Segurança da conta</h2><p>Encerre o acesso em todos os dispositivos, incluindo este.</p></div></div><div className="settings-content"><Button variant="danger" busy={logoutAll.isPending} onClick={() => { if (window.confirm('Encerrar todas as sessões da sua conta? Você precisará entrar novamente.')) logoutAll.mutate(); }}><LogOut size={16} />Encerrar todas as sessões</Button></div></section></>;
}
