import { useState, useDeferredValue, type FormEvent } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { Plus, Search, Columns3, List, CalendarDays, Pencil, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { api, ApiError } from '../lib/api';
import { useWorkspace, useWorkspaceQuery, useRefreshWorkspace, useWorkspacePath } from '../lib/session';
import type { Task, Project, TeamResult, PageResult, Status } from '../lib/types';
import { statusLabel, priorityLabel, dateOnly } from '../lib/format';
import { Avatar, Button, Field, Modal, PageHeading, EmptyState, Loading, ErrorState, StatusBadge, PriorityBadge, Pagination } from '../components/ui';
export function TasksPage() {
  const [searchParams] = useSearchParams(); const { workspace } = useWorkspace(); const path = useWorkspacePath(); const refresh = useRefreshWorkspace();
  const [search, setSearch] = useState(''); const deferredSearch = useDeferredValue(search);
  const [projectId, setProjectId] = useState(searchParams.get('projeto') || ''); const [status, setStatus] = useState(''); const [mine, setMine] = useState(false); const [page, setPage] = useState(1);
  const [view, setView] = useState<'board' | 'list'>('board'); const [modal, setModal] = useState(searchParams.get('nova') === '1'); const [editing, setEditing] = useState<Task | null>(null);
  const parameters = new URLSearchParams({ page: String(page), pageSize: '30' });
  if (deferredSearch) parameters.set('search', deferredSearch); if (projectId) parameters.set('projectId', projectId); if (status) parameters.set('status', status); if (mine) parameters.set('mine', 'true');
  const query = useWorkspaceQuery<PageResult<Task>>('tasks', '/tasks', `?${parameters}`);
  const projectsQuery = useWorkspaceQuery<Project[]>('projects', '/projects'); const membersQuery = useWorkspaceQuery<TeamResult>('members', '/members');
  const projects = (projectsQuery.data || []).filter(p => p.status === 'ACTIVE'); const members = (membersQuery.data?.members || []).filter(m => m.role !== 'VIEWER');
  const canWrite = workspace.role !== 'VIEWER';
  const save = useMutation({ mutationFn: (body: unknown) => api(path(`/tasks${editing ? `/${editing.id}` : ''}`), { method: editing ? 'PATCH' : 'POST', body }), onSuccess: async () => { await refresh(); setModal(false); if (!editing) setPage(1); toast.success(editing ? 'Tarefa atualizada.' : 'Tarefa criada.'); }, onError: async (error: Error) => { toast.error(error.message); if (error instanceof ApiError && error.code === 'STALE_VERSION') await refresh(); } });
  const change = useMutation({ mutationFn: ({ task, status, remove }: { task: Task; status?: Status; remove?: boolean }) => api(path(`/tasks/${task.id}`), { method: remove ? 'DELETE' : 'PATCH', body: { version: task.version, ...(status ? { status } : {}) } }), onSuccess: async () => { if (query.data?.items.length === 1 && page > 1) setPage(page - 1); await refresh(); toast.success('Tarefa atualizada.'); }, onError: async (error: Error) => { toast.error(error.message); await refresh(); } });
  function open(task: Task | null) { setEditing(task); setModal(true); }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget));
    save.mutate({ ...data, dueDate: data.dueDate || null, assigneeMembershipId: data.assigneeMembershipId || null, ...(editing ? { version: editing.version } : {}) });
  }
  function remove(task: Task) { if (window.confirm(`Excluir a tarefa "${task.title}"? Esta ação não pode ser desfeita.`)) change.mutate({ task, remove: true }); }
  const statusSelect = (task: Task) => <select className="compact-select" aria-label={`Status de ${task.title}`} value={task.status} disabled={!canWrite || change.isPending} onChange={e => change.mutate({ task, status: e.target.value as Status })}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>;
  return <><PageHeading eyebrow="PEQUENOS PASSOS, GRANDES ENTREGAS" title="Tarefas" description="Saiba o que fazer, quem está fazendo e o que já foi entregue.">{canWrite && <Button onClick={() => open(null)}><Plus size={17} />Nova tarefa</Button>}</PageHeading>
    <div className="task-toolbar"><label className="search-input"><Search size={17} /><input aria-label="Buscar tarefas" placeholder="Buscar uma tarefa..." value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></label><select aria-label="Filtrar por projeto" value={projectId} onChange={e => { setProjectId(e.target.value); setPage(1); }}><option value="">Todos os projetos</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Filtrar por status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Todos os status</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label className="checkbox-label"><input type="checkbox" checked={mine} onChange={e => { setMine(e.target.checked); setPage(1); }} />Minhas tarefas</label><div className="segmented view-toggle"><button aria-label="Visualizar em quadro" className={view === 'board' ? 'selected' : ''} onClick={() => setView('board')}><Columns3 size={17} /></button><button aria-label="Visualizar em lista" className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}><List size={17} /></button></div></div>
    {query.isPending ? <Loading /> : query.error ? <ErrorState error={query.error} retry={query.refetch} /> : !query.data.items.length ? <div className="panel"><EmptyState title="Tudo começa com uma tarefa." description="Crie uma tarefa ou ajuste os filtros para encontrar o que procura.">{canWrite && <Button onClick={() => open(null)}><Plus size={16} />Criar tarefa</Button>}</EmptyState></div> : view === 'board' ? <div className="kanban">{(['TODO', 'IN_PROGRESS', 'DONE'] as Status[]).map(column => { const tasks = query.data.items.filter(task => task.status === column); return <section className={`kanban-column column-${column}`} key={column}><div className="kanban-heading"><span><i className="status-dot" />{statusLabel[column]}<b>{tasks.length}</b></span>{canWrite && <button className="icon-button" aria-label={`Adicionar tarefa - ${statusLabel[column]}`} onClick={() => open(null)}><Plus size={16} /></button>}</div><div className="kanban-cards">{tasks.map(task => <article className="task-card" key={task.id}><div className="task-card-top"><span className={`project-tag color-${task.project.color}`}>{task.project.name}</span><PriorityBadge priority={task.priority} /></div><button className="task-card-title" onClick={() => open(task)}>{task.title}</button>{task.description && <p>{task.description}</p>}<div className="task-card-meta"><span><CalendarDays size={13} />{dateOnly(task.dueDate)}</span>{task.assignee ? <Avatar name={task.assignee.user.name} small /> : <span className="unassigned">Sem responsável</span>}</div><div className="task-card-footer">{statusSelect(task)}{canWrite && <button className="icon-button danger-text" disabled={change.isPending} aria-label={`Excluir tarefa ${task.title}`} onClick={() => remove(task)}><Trash2 size={14} /></button>}</div></article>)}{!tasks.length && <div className="column-empty">Nenhuma tarefa nesta página.</div>}</div></section>; })}</div> : <div className="panel table-scroll"><table className="data-table"><thead><tr><th>Tarefa</th><th>Responsável</th><th>Prazo</th><th>Prioridade</th><th>Status</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{query.data.items.map(task => <tr key={task.id}><td><button className="task-title" onClick={() => open(task)}>{task.title}</button><span className="table-subtitle">{task.project.name}</span></td><td>{task.assignee?.user.name || 'Não atribuída'}</td><td className="nowrap">{dateOnly(task.dueDate)}</td><td><PriorityBadge priority={task.priority} /></td><td>{statusSelect(task)}</td><td>{canWrite && <div className="inline-actions"><button className="icon-button" aria-label={`Editar tarefa ${task.title}`} onClick={() => open(task)}><Pencil size={15} /></button><button className="icon-button danger-text" aria-label={`Excluir tarefa ${task.title}`} disabled={change.isPending} onClick={() => remove(task)}><Trash2 size={15} /></button></div>}</td></tr>)}</tbody></table></div>}
    {query.data && <><Pagination page={page} total={query.data.total} pageSize={30} onChange={setPage} />{view === 'board' && query.data.total > 30 && <p className="muted small-text">O quadro mostra as tarefas da página atual. Navegue pelas páginas para ver as demais.</p>}</>}
    <Modal open={modal} onOpenChange={value => { if (!save.isPending) setModal(value); }} title={editing ? (canWrite ? 'Editar tarefa' : 'Detalhes da tarefa') : 'Qual é o próximo passo?'} description="Uma boa tarefa tem um resultado claro e uma pessoa responsável.">{projectsQuery.isPending || membersQuery.isPending ? <Loading /> : projectsQuery.error || membersQuery.error ? <ErrorState error={(projectsQuery.error || membersQuery.error)!} retry={() => { projectsQuery.refetch(); membersQuery.refetch(); }} /> : !projects.length && !editing ? <EmptyState title="Primeiro, um projeto." description="As tarefas precisam estar vinculadas a um projeto ativo."><Link className="button primary" to="/app/projetos">Ir para projetos</Link></EmptyState> : <form key={editing?.id || 'new'} onSubmit={submit}><fieldset disabled={!canWrite || save.isPending}><Field label="Título *"><input name="title" required minLength={2} maxLength={160} defaultValue={editing?.title} placeholder="Ex.: Preparar proposta inicial" /></Field><Field label="Descrição"><textarea name="description" rows={3} maxLength={5000} defaultValue={editing?.description} placeholder="Contexto, detalhes e resultado esperado." /></Field><Field label="Projeto *"><select name="projectId" required defaultValue={editing?.projectId || projectId || projects[0]?.id}>{projects.map(project => <option value={project.id} key={project.id}>{project.name}</option>)}</select></Field><div className="form-grid"><Field label="Responsável"><select name="assigneeMembershipId" defaultValue={editing?.assigneeMembershipId || ''}><option value="">Não atribuída</option>{members.map(member => <option key={member.id} value={member.id}>{member.user.name}</option>)}</select></Field><Field label="Prazo"><input type="date" name="dueDate" min="1900-01-01" max="9999-12-31" defaultValue={editing?.dueDate?.slice(0, 10) || ''} /></Field><Field label="Status"><select name="status" defaultValue={editing?.status || 'TODO'}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Prioridade"><select name="priority" defaultValue={editing?.priority || 'MEDIUM'}>{Object.entries(priorityLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div></fieldset>{save.error && <p className="form-error" role="alert">{save.error.message}</p>}<div className="dialog-actions"><Button type="button" variant="secondary" disabled={save.isPending} onClick={() => setModal(false)}>{canWrite ? 'Cancelar' : 'Fechar'}</Button>{canWrite && <Button busy={save.isPending}>{editing ? 'Salvar alterações' : 'Criar tarefa'}</Button>}</div></form>}</Modal>
  </>;
}
