import test from 'node:test';
import assert from 'node:assert/strict';
import { assertTenant, requireRole, requireCapacity, assertRoleChange, calendarDate, subscriptionPlan, assertVersion, assertInvitationEmail } from '../../apps/api/src/domain/policies.mjs';
const fails = (fn, status) => assert.throws(fn, error => error.status === status);
test('tenant: accepts matching workspace', () => assert.doesNotThrow(() => assertTenant({ workspaceId: 'A' }, 'A')));
test('tenant: foreign workspace is hidden', () => fails(() => assertTenant({ workspaceId: 'B' }, 'A'), 404));
test('tenant: missing resource is hidden', () => fails(() => assertTenant(null, 'A'), 404));
for (const role of ['OWNER', 'ADMIN']) test(`role: ${role} can manage`, () => assert.doesNotThrow(() => requireRole(role, ['OWNER', 'ADMIN'])));
for (const role of ['MEMBER', 'VIEWER', 'INVALID']) test(`role: ${role} cannot manage`, () => fails(() => requireRole(role, ['OWNER', 'ADMIN']), 403));
test('quota: accepts exactly the free project limit', () => assert.doesNotThrow(() => requireCapacity('FREE', 'projects', 2)));
test('quota: refuses project overflow', () => fails(() => requireCapacity('FREE', 'projects', 3), 409));
test('quota: unknown plans never grant PRO', () => fails(() => requireCapacity('ENTERPRISE', 'projects', 3), 409));
test('quota: PRO project limit', () => fails(() => requireCapacity('PRO', 'projects', 30), 409));
test('quota: pending invites reserve seats', () => fails(() => requireCapacity('FREE', 'members', 3), 409));
test('quota: task limit', () => fails(() => requireCapacity('FREE', 'tasks', 100), 409));
test('quota: invalid counters fail closed', () => fails(() => requireCapacity('FREE', 'tasks', -1), 400));
test('roles: owner may demote admin', () => assert.doesNotThrow(() => assertRoleChange('OWNER', 'ADMIN', 'MEMBER', false)));
test('roles: admin cannot promote', () => fails(() => assertRoleChange('ADMIN', 'MEMBER', 'ADMIN', false), 403));
test('roles: owner cannot demote self', () => fails(() => assertRoleChange('OWNER', 'OWNER', 'MEMBER', true), 400));
test('roles: owner change must use dedicated flow', () => fails(() => assertRoleChange('OWNER', 'MEMBER', 'OWNER', false), 400));
test('calendar: preserves date at UTC midnight', () => assert.equal(calendarDate('2026-09-20').toISOString(), '2026-09-20T00:00:00.000Z'));
test('calendar: valid leap day', () => assert.equal(calendarDate('2028-02-29').toISOString().slice(0,10), '2028-02-29'));
for (const date of ['2026-02-29', '2026-13-01', '2026-04-31', '20/09/2026', '2026-9-2', '1899-01-01']) test(`calendar: rejects ${date}`, () => fails(() => calendarDate(date), 400));
test('calendar: accepts null', () => assert.equal(calendarDate(null), null));
for (const status of ['active', 'trialing']) test(`billing: ${status} grants PRO with known price`, () => assert.equal(subscriptionPlan(status, true), 'PRO'));
for (const status of ['past_due', 'unpaid', 'canceled', 'incomplete', 'incomplete_expired', 'paused']) test(`billing: ${status} grants only FREE`, () => assert.equal(subscriptionPlan(status, true), 'FREE'));
test('billing: unrelated price grants only FREE', () => assert.equal(subscriptionPlan('active', false), 'FREE'));
test('concurrency: matching version accepted', () => assert.doesNotThrow(() => assertVersion(2, 2)));
test('concurrency: stale version rejected', () => fails(() => assertVersion(1, 2), 409));
test('invites: email comparison is canonical', () => assert.doesNotThrow(() => assertInvitationEmail(' Team@Example.com ', 'team@example.com')));
test('invites: cannot accept invitation to another user', () => fails(() => assertInvitationEmail('a@example.com', 'b@example.com'), 403));
